#pragma once

#include "Models/Gear/Gear.h"
#include "Models/Pendulum/Pendulum.h"
#include "Models/ClockFace/ClockFace.h"
#include "Models/Pendulum/Pendulum.h"
#include "Models/HoursIndicator/HoursIndicator.h"
#include "Models/SecIndicator/SecIndicator.h"
#include "Models/MinIndicator/MinIndicator.h"
#include "Models/Lamp/Lamp.h"
#include "Models/MinIndicator/MinIndicator.h"
#include "Models/Clock/Clock.h"
#include "Models/Bird/Bird.h"
#include "Models/Clockdoor/Clockdoor.h"
#include "Models/Clockdoorleft/Clockdoorleft.h"
#include "Models/MinIndicator/MinIndicator.h"
#include "Models/Lamp/Lamp.h"
#include "Models/Backstage/Backstage.h"
#include "Models/Chair/Chair.h"
#include "Models/Table/Table.h"
#include "Models/Wardrobe/Wardrobe.h"
#include "Models/Carpet/Carpet.h"

